#! /bin/bash

####################################################################################################
# 
# PyElectronic - Python Electronic Tools 
# Copyright (C) Salvaire Fabrice 2012 
# 
####################################################################################################

root_dir=`python -c "import os ; print os.path.dirname(os.path.dirname(os.path.realpath('$0')))"`

for i in `find ${root_dir} -name '*.py' | sort -n` ; do
  # echo Check $i
  grep -L 'PyElectronic - Python Electronic Tools' $i;
done

####################################################################################################
#
# End
#
####################################################################################################
